[tool.poetry]
name = "gofannon"
version = "0.1.0"
description = "A collection of tools for LLMs"
authors = ["Trevor Grant <trevor.d.grant@gmail.com>"]
license = "ASFv2"
readme = "README.md"
packages = [{include = "gofannon"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.60.2"
requests = "^2.32.3"
GitPython = "^3.1.43"
python-dotenv = "^1.0.1"
pytest = "^8.3.4"
langchain = "^0.3.16"
smolagents = "^1.6.0"
pydantic = "^2.10.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
